[control]
control-node ansible_host=localhost ansible_connection=local

[web]
web-server ansible_host=35.95.72.1

[app]
app-server ansible_host=35.95.60.66

[db]
db-server ansible_host=35.93.226.130

[application:children]
web
app

[all_servers:children]
application
db

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
