[control]
control-node ansible_host=16.148.15.242

[web]
web-server ansible_host=54.187.220.32

[app]
app-server ansible_host=35.95.131.96

[db]
db-server ansible_host=16.148.44.21

[application:children]
web
app

[all_servers:children]
application
db

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519

