[control]
control-node ansible_host=172.31.40.146

[web]
web-server ansible_host=172.31.32.25

[app]
app-server ansible_host=172.31.37.229

[db]
db-server ansible_host=172.31.32.132

[application:children]
web
app

[all_servers:children]
application
db

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
